import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create a Quote!</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/fhn2cew.css"></link>
      </Head>
      <main id="test" className="flex min-h-screen flex-col items-center justify-center bg-amber-50">
        <div className="container flex flex-col items-center justify-center p-4">
          {/* <div className="md:max-w-2xl"> */}
          <div className="w-80">
            <h1 className="text-xl font-bold">Your Quote: </h1>
            <div>
              And of course, said the Queen, 'it goes on,
              not a week passing without something of interest,
              a scandal, a cover-up or even a war. And since this
              is one's birthday you must not even think of looking
              peeved' - the prime minister was studying the
              ceiling and the home secretary the carpet - 'for
              one has a long perspective and it was ever thus.
              <span className="highlight"> At eighty things do not occur; they recur.</span>
            </div>
            <div className="h-5"></div>
            <hr></hr>
            <div className="h-5"></div>
            <h1 className="text-xl font-bold">Your Quote: </h1>
            <div>
              ...it is essential to begin by reckoning with the fact
              that one of the foundations of Western culture is leisure.
              That much, at least, can be learnt from the first chapter
              of Aristotle's Metaphysics. And even the history of the word
              attests the fact:
              <span className="highlight"> for leisure in Greek is skole,
                and in Latin scola, the English "school."</span>
            </div>
            <div className="h-5"></div>
            <hr></hr>
            <div className="h-5"></div>
            <h1 className="text-xl font-bold">Your Quote: </h1>
            <div>
              Acedia was reckoned among the vitia capitalia, as one of
              the seven capital or cardinal sins, for they were not
              called "capital" because of the best-known rendering of caput;
              <span className="highlight"> caput certainly means "head", but it also means "source" or
                "spring" -and that is the meaning in this case. </span>They are sins
              from which other faults follow "naturally" one is tempted to
              say, as from a source.
            </div>
          </div>
        </div>
      </main >
    </>
  );
}
