import Head from "next/head";
// import Link from "next/link";
import { useState } from "react";

export default function Home() {
  const [textValue, setTextValue] = useState<string>('');

  // Handle input change
  const handleInputChange = (event: React.ChangeEvent<HTMLTextAreaElement>): void => {
    setTextValue(event.target.value);
  };

  // Function to process the text value
  const processTextValue = () => {
    const regex = /\*\*(.*?)\*\*/g;
    let processed = textValue.replace(regex, (_, matchedText) => `<span class="highlight">${matchedText}</span>`);
    processed = processed.replace(/\n/g, '<br />');
    return processed;
  }


  const processedValue = processTextValue();

  return (
    <>
      <Head>
        <title>Create a Quote!</title>
        {/* <link href="https://use.typekit.net/fhn2cew.css" rel="stylesheet" /> */}
        {/* <link rel="stylesheet" href="https://use.typekit.net/fhn2cew.css"></link> */}
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center p-4">
          {/* <div className="md:max-w-2xl"> */}
          <h1 className="text-xl font-bold">Quote Generator: </h1>
          <div className="h-4"></div>
          <div className="border-amber-100 border-2 bg-amber-50 w-80 aspect-[9/11] p-8 flex flex-col items-center justify-center">
            <div className="w-full break-normal" dangerouslySetInnerHTML={{ __html: processedValue }}></div>
          </div>
          <div className="h-4"></div>
          <div className="w-80">
            <div className=" py-2">
              <p className="font-bold">Paste quote below:</p>
              <p>Text within <span className="highlight">**two asterisks**</span> will be highlighted.</p>
            </div>
            {/* <textarea className="border-amber-100 border-2 w-full p-4"></textarea> */}
            {/* Render the input */}
            <textarea
              className="border-amber-100 border-2 w-full p-4"
              value={textValue}
              onChange={handleInputChange}
              placeholder="Type something..."
            />
          </div>
        </div>
      </main >
    </>
  );
}
